app = "little-complex-bot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[deploy]
  strategy = "immediate"

[[vm]]
  size = "shared-cpu-1x"
  memory = "2gb"
  cpus = 1
